name: redarx
description: Experimental State management inspired by Redux, ngrx, André Stalz work & Parsley
version: 0.6.0
author: Erick G. <erick@rxlabz.com>
homepage: https://github.com/rxlabz/redarx

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  meta: '>=1.0.4 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
