name: redarx
description: Experimental State management inspired by Parsley / Redux/ ngrx & André Stalz work
version: 0.2.1
author: Erick G. <erick@rxlabz.com>
homepage: https://rxla.bz

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
